### ISSUE TITLE
Extract "Engine" class

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1749]
To be used internally in the VisModel and also in the upcoming `carto.leaflet.CartoLayerGroup` and `carto.googleMaps.CartoLayerGroup`.

![carto js engine idea](https://user-images.githubusercontent.com/390398/30275332-4aa1b2e4-9701-11e7-9e3f-5e003b0325f1.jpg)

An "Engine" will expose a method that will:

- "Serialise" given layers (and associated queries / analyses / dataviews) and send requests to Maps API.
- Update given models when request is received.
- Raise errors if something goes wrong.

## Tasks

- [x] Move request limiting responsibility from `src/windshaft/map-base.js` to `src/windshaft/client.js` (https://github.com/CartoDB/cartodb.js/pull/1753). 
- [ ] CartoLayer has a `source` that should be an Analysis node (source or analysis). We're using `sql` and `source` attributes before. Can remove support for `sql` attribute (https://github.com/CartoDB/cartodb.js/issues/1754).
- [ ] Merge `LayersCollection`, `DataviewsCollection`, and `AnalysisCollection` into CartoLayer hierarchy (see drawing above).
  - [ ] Source has `dataviews` and `filters` (might require changes to Windshaft Map).
  - [ ] TBD.

![image](https://user-images.githubusercontent.com/390398/30313681-794157a6-979e-11e7-8309-dd5c80333fd8.png)

- [ ] Extract classes that know how to generate payload for Maps API from an array / collection of layers (this is currently implemented in `src/windshaft/anonymous-map.js#toJSON` and `src/windshaft/named-map.js#toJSON`.
- [ ] Extract "Engine" class:
  - [ ] Mutate `src/windshaft/map-base.js` into the new "Engine" classes that uses `src/windshaft/client.js` and `src/windshaft-integration/model-updater.js` internally.
  - [ ] `VisModel#reload` uses the new "Engine".
  - [ ] `VisModel#setOk` and `VisModel#setErrors` are "handled" by `VisModel` instead of by `src/windshaft-integration/model-updater.js`.

**Comment by alonsogarciapablo** [comment]
I exploded this issue into smaller ones so this one doesn't make sense anymore.
