### ISSUE TITLE
[v4-remove-analysisCollection]

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb.js#1762]
Now that `CartoDBLayer`, `TorqueLayer` models, and `DataviewModel` model point to an analysis/source model (and expose a `getSource` method), we can get rid of the internal `AnalysisCollection` and extract analyses from layers and dataviews. This is something very beneficial for https://github.com/CartoDB/cartodb.js/issues/1774.

![image](https://user-images.githubusercontent.com/390398/30749020-5e7c7cfe-9fb2-11e7-949c-7bd077fdf8cd.png)

## Tasks:

- [x] https://github.com/CartoDB/cartodb.js/issues/1763
- [ ] https://github.com/CartoDB/cartodb.js/issues/1787
- [ ] https://github.com/CartoDB/cartodb.js/issues/1788
- [ ] https://github.com/CartoDB/cartodb.js/issues/1789
- [ ] https://github.com/CartoDB/cartodb.js/issues/1790

**Comment by IagoLast** [comment]
since both (serializer and ModelUpdater) needs access to the analysis collection I think we should keep it in the `analysisService` which will have the following responsibilities:

* Create an analysis from a json definition.
* Keep a list with the existing analysis (One service and list per engine)
* Utility functions related to the analyses

**Comment by IagoLast** [comment]
## About point 2

We should create a folder named `model-updater` this folder will work similar to the `maps-
serializer` one.

Inside this folder we got 3 files: 'layers-updater', `dataviews-updater` and `analysis-updater`  each one witha  public `.update()` method allowing easy unit-testing them.

The model-updater main method should be something like this:
```javascript 
ModelUpdater.prototype.updateModels = function (windshaftMap, sourceId, forceFetch) {
  this._layerUpdater.update(params...);
  this._dataViewUpdater.update(params...);
  this._analysisUpdater.update(params...);
  // TODO: Notify the engine to update the view?
};
```

#### AnalysisUpdater

Instead keeping a list with all the created analyses, the `analysesUpdater.update()` should receive the following parameters:

  - the windshaft response
  - the layerCollection
  - the dataviewCollection

And extract all the `analyses` from the layers and dataviews collections updating each one.

Currently the analysisModel is updated using the `.set`, 'setOk` and the `setError` methods:

**looks like setError is not being used!)**


what about adding an `update` method? 



cc @alonsogarciapablo @ivanmalagon @Jesus89

**Comment by alonsogarciapablo** [comment]
@IagoLast that's a great (and very tempting) idea that we can tackle once we have something working end to end :1st_place_medal:. For now, I think we can get by with the current implementation of the `ModelUpdater` and this part of what you're suggesting:

> And extract all the analyses from the layers and dataviews collections updating each one.

This will get us closer to not depending on the `AnalysisCollection` and being able to extract that `Engine` class...

**Comment by alonsogarciapablo** [comment]
This issue was exploded into smaller issue, so closing it!
