### ISSUE TITLE
Add browserify

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb.js#699]
_edit: Added scope & planning, will be updated continuously  /@viddo_

Considering the browserify'ing of the source code will imply a lot of changes to existing source, we want to avoid epic pull-requests and changes that are hard to control. 
Thus, the following approach will be taken:
- Create separate "baseline" branch (`v4-browserify`) while this issue is in WIP (branch off `v4`), copy src+specs to the new dir structure so PRs against this branch shows as changes and not new files
- Branch of this baseline branch for each significant change, and create pull-request to merge back to the WIP baseline (i.e. `v4-browserify`)
- Each source file will be copied to a new location (e.g. `src-browserify/`), and modified from there, instead of trying to modify the source right away
- Once all code is migrated, reviewed & ready, merge `v4-browserify` to `v4`

**Also, in general:**
- Any eventual changes happening on `v4` meanwhile will be updated/merged to `v4-browserify` manually
- Use npm packages instead of manually have to keep track of vendor files (where possible)
- One concept/class/object per file, following node/commonjs conventions/best-practices
- But maintain current directory layout, to ease understanding of where move code went
- Avoid modify any existing code unless required to due to the re-organization

**Tasks:**
- [x] Setup boilplate; browserify build, tests integration etc. :point_right: #723
- [x] ~~Migrate core bundle #723~~, removed in :point_down: #738 
- [x] Migrate standard bundle (cartodb.js) :point_right: #738 
- [x] fix banner bug screwing up source-maps b59e684
- [x] Migrate torque bundle (cartodb.mod.torque.js) :point_right: #754
- [x] Migrate odyssey bundle  (cartodb.mod.odyssey.js) :point_right: #755
- [x] Update cdb.VERSION on build :point_right: 295ee6d
- [x] Support source-maps in minimized dist file; add [exorcist](https://github.com/thlorenz/exorcist) to extract source maps before uglify task :point_right: #757
- [x] ~~Add D3.js? :point_right: #718 / #719~~ follow [browserify idioms instead, postponed](https://github.com/CartoDB/cartodb.js/pull/719#issuecomment-153418701)
- [x] cleanup after all bundles are migrated :point_right: #722
- [x] fix torque loading jquery from cartodb.js instead of containing it itself
- [x] update `develop` -->  `v4` --> `v4-browserify`, migrate any changes done initially branch off
- [x] merge `v4-browserify` to `v4`

---

Out-of-scope/things encountered that perhaps maybe should be addressed in the future:
- Code improvements (TBD later as part of redoing the APIs)
- Replace Jasmine with [Tape](https://github.com/substack/tape)+[testling](https://ci.testling.com) to have cross-browser testing
- support npm/node usage?
  - requires replacing `window.` usages w/ `global`
  - update pkg.main reference to point to a proper entry file

**Comment by xavijam** [comment]
Will you take care of https://github.com/CartoDB/cartodb.js/issues/700'

**Comment by viddo** [comment]
I have it on my radar, but not sure if I want to add it to the scope here. Anyway, I'll reassign it to me

**Comment by viddo** [comment]
merged (to `v4`) in 4033ab2f4245e351700ea9460641f6de264ad5d9
