### ISSUE TITLE
Add time-series widget (first iteration)

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb.js#786]
Main issue to keep track of WIP

- [x] Required layout changes for new widget #783
- [x] Placeholder views for the various concepts (using fake model/data); controls (play/pause), step info, histogram chart #787
- [x] Implement default date/time histogram #811
- [x] Histogram: format X-axis labels with time and/or date (needs to adapt to range span+mockups) #843
- [x] Torque: implement animation controls (play/pause, time-marker) #844
- [x] Torque: animation for a selected time-series range #855 + https://github.com/CartoDB/torque/pull/243
- [x] Torque: format time-marker step info (time+date) #855 
- [x] CSS for the various layouts/responsive sizes #879

Windshaft needs to be updated to support date column for histogram data :point_right: https://github.com/CartoDB/Windshaft/issues/405
